language: node_js
node_js:
  - "10"
before_install:
  - chmod +x ./test.sh
  - chmod +x ./build-publish-img.sh
jobs:
  include:
    - stage: test
      script: ./test.sh
    - stage: build and publish
      script: ./build-publish-img.sh